### ISSUE TITLE
Profile Page: Throwing exception for eCardSub@cardfool.com

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#25]
1. Log in as ecardsub@cardfool.com (test)
2. Go to https://staging.cardfool.com/my_account
![screen shot 2015-11-05 at 4 21 58 pm](https://cloud.githubusercontent.com/assets/6485279/10984815/642f4506-83d9-11e5-96a2-489dfa09ccc4.png)

**Comment by granthleslie** [comment]
This is the credit card tokenization issue we've run into because of the Spree version we're on.  We've back-ported that functionality so that it will work with our current Spree version.
https://bitbucket.org/DCI_Studios/cardfool.com-railsdog/commits/25dbc5ec4a4bda1882238d745ba15bba1f8c9e0b
That link is the back-port fix.   I have merged and pushed this to staging.
